"""
modules/agent_planner/domain/task_plan.py
Domain Layer: Entities and Value Objects for LLM Task Planning
"""

from typing import List, Dict, Any, Optional

class ActionStep:
    """Entity representing a single robotic action step in a plan."""
    def __init__(self, tool_name: str, args: Dict[str, Any], voice_prompt: Optional[str] = None):
        if not tool_name:
            raise ValueError("ActionStep must have a valid tool_name.")
        self._tool_name = tool_name
        self._args = args or {}
        self._voice_prompt = voice_prompt

    @property
    def tool_name(self) -> str:
        return self._tool_name

    @property
    def args(self) -> Dict[str, Any]:
        return dict(self._args)

    @property
    def voice_prompt(self) -> Optional[str]:
        return self._voice_prompt

    def __repr__(self) -> str:
        return f"ActionStep(tool='{self._tool_name}', args={self._args})"

class TaskPlan:
    """Aggregate Root representing a multi-step task plan generated by LLM."""
    def __init__(self, plan_summary: str, tasks: List[ActionStep]):
        self._plan_summary = plan_summary
        self._tasks = tasks or []

    @property
    def plan_summary(self) -> str:
        return self._plan_summary

    @property
    def tasks(self) -> List[ActionStep]:
        return list(self._tasks)

    def __repr__(self) -> str:
        return f"TaskPlan(summary='{self._plan_summary}', steps={len(self._tasks)})"
